version: '2'

services:
  app:
    image: 'io:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/readingisgod_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Pstgrs
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8181:8080"
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Pstgrs
      - POSTGRES_DB=readingisgod_db
